// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rubicon_blog.DAL;

namespace Rubicon_blog.DAL.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rubicon_blog.DAL.Domain.BlogPost", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Slug");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Slug = "augmented-reality-ios-application",
                            Body = "The app is simple to use, and will help you decide on your best furniture fit.",
                            CreatedAt = new DateTime(2021, 4, 27, 2, 57, 6, 321, DateTimeKind.Local).AddTicks(8383),
                            Description = "Rubicon Software Development and Gazzda furniture are proud to launch an augmented reality app.",
                            Title = "Augmented Reality iOS Application",
                            UpdatedAt = new DateTime(2021, 4, 27, 2, 57, 6, 324, DateTimeKind.Local).AddTicks(9508)
                        },
                        new
                        {
                            Slug = "augmented-reality-ios-application-2",
                            Body = "The app is simple to use, and will help you decide on your best furniture fit.",
                            CreatedAt = new DateTime(2021, 4, 27, 2, 57, 6, 325, DateTimeKind.Local).AddTicks(313),
                            Description = "Rubicon Software Development and Gazzda furniture are proud to launch an augmented reality app.",
                            Title = "Augmented Reality iOS Application 2",
                            UpdatedAt = new DateTime(2021, 4, 27, 2, 57, 6, 325, DateTimeKind.Local).AddTicks(332)
                        });
                });

            modelBuilder.Entity("Rubicon_blog.DAL.Domain.PostTag", b =>
                {
                    b.Property<string>("BlogPostSlug")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TagSlug")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BlogPostSlug", "TagSlug");

                    b.HasIndex("TagSlug");

                    b.ToTable("PostTags");

                    b.HasData(
                        new
                        {
                            BlogPostSlug = "augmented-reality-ios-application",
                            TagSlug = "ar"
                        },
                        new
                        {
                            BlogPostSlug = "augmented-reality-ios-application",
                            TagSlug = "ios"
                        });
                });

            modelBuilder.Entity("Rubicon_blog.DAL.Domain.Tag", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Slug");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Slug = "ios",
                            Name = "iOS"
                        },
                        new
                        {
                            Slug = "ar",
                            Name = "Augmented Reality"
                        },
                        new
                        {
                            Slug = "gazzda",
                            Name = "Gazzda"
                        });
                });

            modelBuilder.Entity("Rubicon_blog.DAL.Domain.PostTag", b =>
                {
                    b.HasOne("Rubicon_blog.DAL.Domain.BlogPost", "BlogPost")
                        .WithMany("TagList")
                        .HasForeignKey("BlogPostSlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rubicon_blog.DAL.Domain.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagSlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Rubicon_blog.DAL.Domain.BlogPost", b =>
                {
                    b.Navigation("TagList");
                });
#pragma warning restore 612, 618
        }
    }
}
